---
- name: Deploy AWS content
  hosts: aws
  become: true
  tasks:
    - name: Copy AWS index
      copy:
        src: "{{ playbook_dir }}/../files/index-aws.html"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Verify page
      uri:
        url: "http://{{ ansible_host }}/"
        return_content: true
      register: resp
    - name: Assert content
      assert:
        that: "'Welcome to AWS' in resp.content"
        fail_msg: "AWS page did not contain expected text"

- name: Deploy Azure content
  hosts: azure
  become: true
  tasks:
    - name: Copy Azure index
      copy:
        src: "{{ playbook_dir }}/../files/index-azure.html"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Verify page
      uri:
        url: "http://{{ ansible_host }}/"
        return_content: true
      register: resp
    - name: Assert content
      assert:
        that: "'Welcome to Azure' in resp.content"
        fail_msg: "Azure page did not contain expected text"

