---
- name: Deploy AWS page
  hosts: aws
  become: true
  tasks:
    - copy:
        src: "{{ playbook_dir }}/../files/index-aws.html"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: "0644"
    - service:
        name: nginx
        state: restarted
    - uri:
        url: "http://{{ ansible_host }}/"
        return_content: true
      register: resp_aws
    - assert:
        that: "'Welcome to AWS' in resp_aws.content"
        fail_msg: "AWS page missing expected text"

- name: Deploy Azure page
  hosts: azure
  become: true
  tasks:
    - copy:
        src: "{{ playbook_dir }}/../files/index-azure.html"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: "0644"
    - service:
        name: nginx
        state: restarted
    - uri:
        url: "http://{{ ansible_host }}/"
        return_content: true
      register: resp_az
    - assert:
        that: "'Welcome to Azure' in resp_az.content"
        fail_msg: "Azure page missing expected text"
